ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-dev.srikanthchalla.online
CATALOGUE_HOST: catalogue-dev.srikanthchalla.online
REDIS_HOST: redis-dev.srikanthchalla.online
USER_HOST: user-dev.srikanthchalla.online
CART_HOST: cart-dev.srikanthchalla.online
MYSQL_HOST: mysql-dev.srikanthchalla.online
SHIPPING_HOST: shipping-dev.srikanthchalla.online
RABBITMQ_HOST: rabbitmq-dev.srikanthchalla.online
PAYMENT_HOST: payment-dev.srikanthchalla.online
